# Generated by Django 4.2.3 on 2023-08-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='completed',
        ),
    ]
