# Generated by Django 4.2.3 on 2023-08-17 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 13, 30, 43, 611440, tzinfo=datetime.timezone.utc)),
        ),
    ]
