# Generated by Django 4.2.3 on 2023-08-17 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_body_task_header_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 14, 44, 3, 383525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_colour',
            field=models.TextField(choices=[('#34ccff', 'blue-theme'), ('#e4f78f', 'green-theme'), ('#ffc983', 'orange-theme'), ('#ffa0a1', 'red-theme'), ('#b99aff', 'purple-theme')], default='#ffc983', max_length=7),
        ),
    ]
