# Generated by Django 4.2.3 on 2023-08-18 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_task_due_date_alter_task_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 8, 55, 59, 632263, tzinfo=datetime.timezone.utc)),
        ),
    ]
