# Generated by Django 4.2.3 on 2023-08-22 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_userprofile_full_name_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 10, 4, 32, 175444, tzinfo=datetime.timezone.utc)),
        ),
    ]
