# Generated by Django 4.2.3 on 2023-08-23 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_task_due_date_alter_task_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 7, 56, 11, 299652, tzinfo=datetime.timezone.utc)),
        ),
    ]
