# Generated by Django 4.2.3 on 2023-08-23 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_userprofile_full_name_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 8, 7, 31, 747117, tzinfo=datetime.timezone.utc)),
        ),
    ]
