# Generated by Django 4.2.3 on 2023-08-23 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_task_due_date_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='base.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 9, 50, 52, 980394, tzinfo=datetime.timezone.utc)),
        ),
    ]
