# Generated by Django 4.2.3 on 2023-08-27 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_userprofile_profile_pic_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='base.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 8, 16, 6, 847401, tzinfo=datetime.timezone.utc)),
        ),
    ]
