# Generated by Django 4.2.3 on 2023-08-27 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_profilepic_user_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='task_manager/public/profile_pics'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 8, 40, 58, 454486, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
