# Generated by Django 4.2.3 on 2023-08-27 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_task_due_date_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_manager/public/profile_pics'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 9, 9, 24, 175309, tzinfo=datetime.timezone.utc)),
        ),
    ]
