# Generated by Django 4.2.3 on 2023-08-27 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_profileimage_image_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='task_manager/public/profile_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 9, 19, 4, 24851, tzinfo=datetime.timezone.utc)),
        ),
    ]
