# Generated by Django 4.2.3 on 2023-08-28 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_profileimage_alt_text_alter_profileimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 9, 33, 21, 44662, tzinfo=datetime.timezone.utc)),
        ),
    ]
