# Generated by Django 4.2.3 on 2023-08-29 07:51

import base.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_profileimage_image_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 7, 51, 13, 2587, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=base.models.upload_to),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
