# Generated by Django 4.2.3 on 2023-08-29 09:10

import base.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_task_due_date_alter_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 9, 10, 58, 389631, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no_pfp.jpeg', upload_to=base.models.upload_to),
        ),
    ]
