# Generated by Django 4.2.3 on 2023-09-10 08:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0043_alter_task_due_date_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 8, 7, 10, 586071, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserFriending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_friended', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('friending_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_friended'],
            },
        ),
        migrations.AddConstraint(
            model_name='userfriending',
            constraint=models.UniqueConstraint(fields=('user_id', 'friending_user_id'), name='unique followers'),
        ),
    ]
